imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        default_locale: "%locale%"
        default_timezone: "%default_timezone%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    #bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        lessphp:
            apply_to: "\.less$"
            formatter: "compressed"
            preserve_comments: false
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
#doctrine:
#    dbal:
#        driver:   "%database_driver%"
#        host:     "%database_host%"
#        port:     "%database_port%"
#        dbname:   "%database_name%"
#        user:     "%database_user%"
#        password: "%database_password%"
#        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

#    orm:
#        auto_generate_proxy_classes: "%kernel.debug%"
#        auto_mapping: true

doctrine_mongodb:
    connections:
        default:
            server: %mongo_server%
            options: {}
    default_database: %mongo_database%
    document_managers:
        default:
            auto_mapping: true

stof_doctrine_extensions:
    mongodb:
        default:
            sluggable: true
            timestampable: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_user:
    db_driver: mongodb
    firewall_name: main
    user_class: FreeBet\Bundle\UserBundle\Document\User
    service:
        user_manager: free_bet.user_manager
    profile:
        form:
            type: freebet_user_profile
    registration:
        form:
            type: freebet_user_registration

knp_menu:
    twig:
        template: FreeBetUIBundle:Layout:_menu.html.twig

knp_paginator:
    template:
        pagination: FreeBetUIBundle:Layout:_paginator.html.twig
        sortable: FreeBetUIBundle:Layout:_sortable_link.html.twig

free_bet_competition:
    mapping_events:
        soccer: FreeBet\Bundle\SoccerBundle\Document\Match

free_bet_soccer_league:
    scrapers:
        lequipe:
            configuration:
                - { name: ligue-1-2014, url: http://www.lequipe.fr/Football/FootballResultat47991.html }
                - { name: premiere-league-2014, url: http://www.lequipe.fr/Football/FootballResultat48386.html }
                - { name: liga-2014, url: http://www.lequipe.fr/Football/FootballResultat48837.html }
                - { name: serie-a-2014, url: http://www.lequipe.fr/Football/FootballResultat49162.html }
                - { name: bundesliga-2014, url: http://www.lequipe.fr/Football/FootballResultat48572.html }